version: '3'

services:
  proxy:
    build: ./envoy
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - grpc-todolist
  server:
    build: ./server
    image: todo-grpc-server:v1
    restart: unless-stopped
    networks:
      - grpc-todolist
networks:
  grpc-todolist:
    driver: bridge
